name: Release
on:
  schedule:
    - cron: "5 */12 * * *"
  push:
    branches:
      - main


jobs:
  Discord:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['3.8']
    steps:
    - uses: actions/checkout@v2

    - name: Build Google Chrome
      run: ./build.sh
       
    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: Google Chrome Stable AppImage Builds
        automatic_release_tag: stable
        prerelease: false
        draft: false
        files: ./google-chrome/dist/Google-Chrome-*-x86_64.AppImage*
        repo_token: ${{ secrets.GITHUB_TOKEN }}
